"""check status

Revision ID: 05525411e845
Revises: 1aa5219f3867
Create Date: 2025-06-19 22:05:10.061817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05525411e845'
down_revision = '1aa5219f3867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###
