"""first model uprade

Revision ID: 0ed5539db3cc
Revises: 1914ff7903fb
Create Date: 2025-06-05 13:39:44.793572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed5539db3cc'
down_revision = '1914ff7903fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('county', sa.String(length=255), nullable=True))
        batch_op.drop_column('city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('county')

    # ### end Alembic commands ###
