"""order table nullable

Revision ID: 1aa5219f3867
Revises: fde1465c0406
Create Date: 2025-06-19 18:18:18.511251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa5219f3867'
down_revision = 'fde1465c0406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('customer_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('customer_phone',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('customer_phone',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('customer_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###
