"""migration 3

Revision ID: 247082abf80f
Revises: ec19e660e8ae
Create Date: 2025-06-18 14:04:38.134106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247082abf80f'
down_revision = 'ec19e660e8ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('county', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup_points', schema=None) as batch_op:
        batch_op.drop_column('county')

    # ### end Alembic commands ###
