"""Add cost, phone_number, is_doorstep, delivery_method to PickupPoint

Revision ID: a2f54f184f79
Revises: bb3ca9a1423d
Create Date: 2025-06-09 14:29:04.329117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f54f184f79'
down_revision = 'bb3ca9a1423d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_doorstep', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('delivery_method', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup_points', schema=None) as batch_op:
        batch_op.drop_column('delivery_method')
        batch_op.drop_column('is_doorstep')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('cost')

    # ### end Alembic commands ###
