"""update image upload

Revision ID: e7ee0545e621
Revises: abff114ac862
Create Date: 2025-06-19 11:17:50.477413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7ee0545e621'
down_revision = 'abff114ac862'
branch_labels = None
depends_on = None
image_approval_status_enum = postgresql.ENUM(
    'PENDING', 'APPROVED', 'REJECTED',
    name='imageapprovalstatus'
)

def upgrade():
    image_approval_status_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cloudinary_public_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='imageapprovalstatus'), nullable=False))
        batch_op.add_column(sa.Column('approved_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('approval_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['approved_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('approval_date')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('approval_status')
        batch_op.drop_column('cloudinary_public_id')

    # ### end Alembic commands ###
    image_approval_status_enum.drop(op.get_bind())
