"""migration 2.0

Revision ID: ec19e660e8ae
Revises: a2f54f184f79
Create Date: 2025-06-09 14:48:13.669557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec19e660e8ae'
down_revision = 'a2f54f184f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_person', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup_points', schema=None) as batch_op:
        batch_op.drop_column('contact_person')

    # ### end Alembic commands ###
