"""update image upload

Revision ID: fde1465c0406
Revises: e7ee0545e621
Create Date: 2025-06-19 14:49:33.493644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde1465c0406'
down_revision = 'e7ee0545e621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('is_temporary', sa.Boolean(), nullable=False))
        batch_op.alter_column('order_item_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('order_item_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('is_temporary')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
